apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch
  labels:
    type: local
spec:
  storageClassName: local-pvdata
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/pvdata"